name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-data-pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      working-directory: ./src/etl_pipeline
      run: make init-dev

    - name: Run check
      working-directory: ./src/etl_pipeline
      run: make check

  build-backtesting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      working-directory: ./src/backtest
      run: make init-dev

    - name: Run check
      working-directory: ./src/backtest
      run: make check


  build-cdk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      run: npm ci

    - name: Run check
      run: make check
